name: WGEnderPearlFlag
version: 0.1
description: '"WorldGuard" extension to block enderpearls in specific regions.'
author: BangL
website: http://bangl.de/
depend: [WorldGuard, WorldEdit, WGCustomFlags]
main: de.bangl.wgepf.WGEnderPearlFlagPlugin
